package main

import (
	"fmt"
	"os"
	"strings"
)

// factorInfo describes a single verification factor for the help system.
type factorInfo struct {
	Name        string
	Tier        int
	Summary     string // one-line for help listing
	Description string // full explanation for 'teep help <factor>'
}

// tierInfo describes one verification tier.
type tierInfo struct {
	Number      int
	Name        string // e.g. "Core Attestation"
	Label       string // e.g. "Tier 1: Core Attestation"
	Description string
}

// factorRegistry contains all 21 verification factors in report order.
var factorRegistry = [21]factorInfo{
	// Tier 1: Core Attestation
	{
		Name:    "nonce_match",
		Tier:    1,
		Summary: "Response nonce matches request",
		Description: "Verifies that the nonce returned in the attestation response " +
			"matches the random nonce sent by the client. This prevents replay " +
			"attacks where an attacker presents a stale but valid attestation " +
			"from a previous session.",
	},
	{
		Name:    "tdx_quote_present",
		Tier:    1,
		Summary: "TDX quote is present in response",
		Description: "Checks that the intel_quote field exists in the attestation " +
			"response. The TDX quote is the cryptographic proof generated by " +
			"Intel TDX hardware that the code is running inside a genuine " +
			"Trusted Domain (TD). Without it, no hardware-level attestation " +
			"is possible.",
	},
	{
		Name:    "tdx_quote_structure",
		Tier:    1,
		Summary: "TDX quote parses as valid QuoteV4/V5",
		Description: "Parses the TDX quote binary and verifies it conforms to the " +
			"Intel QuoteV4 or QuoteV5 structure. On success, displays the " +
			"MRTD (Measurement of the initial TD image) prefix — a SHA-384 " +
			"hash of the VM image loaded by the VMM. Comparing MRTD against " +
			"a provider-published reference value is how you detect VM image " +
			"tampering. A malformed quote indicates data corruption or a " +
			"non-genuine attestation source.",
	},
	{
		Name:    "tdx_cert_chain",
		Tier:    1,
		Summary: "Intel root CA certificate chain valid",
		Description: "Verifies the X.509 certificate chain embedded in the TDX " +
			"quote traces back to the Intel SGX/TDX root CA. This proves the " +
			"quote was generated by genuine Intel hardware, not emulated or " +
			"spoofed.",
	},
	{
		Name:    "tdx_quote_signature",
		Tier:    1,
		Summary: "TDX quote signature verified",
		Description: "Verifies the ECDSA signature over the TDX quote body using " +
			"the attesting key from the certificate chain. This ensures the " +
			"quote has not been tampered with since generation.",
	},
	{
		Name:    "tdx_debug_disabled",
		Tier:    1,
		Summary: "Debug bit is 0 (production enclave)",
		Description: "Checks that the TD_ATTRIBUTES debug bit in the TDX quote is " +
			"not set. A debug enclave allows the host to inspect enclave " +
			"memory, which completely undermines confidentiality. Production " +
			"workloads must never run in debug mode.",
	},
	{
		Name:    "signing_key_present",
		Tier:    1,
		Summary: "Signing key present in response",
		Description: "Checks that the signing_key field exists in the attestation " +
			"response. The signing key is the public key generated inside the " +
			"TEE that is used for E2EE key exchange. Without it, encrypted " +
			"communication with the enclave is not possible.",
	},
	// Tier 2: Binding & Crypto
	{
		Name:    "tdx_reportdata_binding",
		Tier:    2,
		Summary: "REPORTDATA binds signing key to enclave",
		Description: "Verifies that the TDX REPORTDATA field contains the Ethereum " +
			"address derived from the signing key (keccak256 of the uncompressed " +
			"secp256k1 public key). This cryptographically binds the signing key " +
			"to the attested enclave, preventing a man-in-the-middle from " +
			"substituting the key while leaving the TDX quote intact. Without " +
			"this binding, E2EE is security theater.",
	},
	{
		Name:    "intel_pcs_collateral",
		Tier:    2,
		Summary: "Intel PCS collateral fetched",
		Description: "Verifies that collateral (TCB info, CRLs) was successfully " +
			"fetched from the Intel Provisioning Certification Service (PCS). " +
			"Collateral is required for TCB currency and revocation checks. " +
			"Skipped in --offline mode or when the Intel PCS is unreachable.",
	},
	{
		Name:    "tdx_tcb_current",
		Tier:    2,
		Summary: "TEE TCB status from Intel PCS",
		Description: "Evaluates the TCB status returned by Intel PCS collateral " +
			"against the TDX quote. Passes for UpToDate and SWHardeningNeeded " +
			"(software mitigations applied). Fails for OutOfDate or Revoked " +
			"(firmware has known vulnerabilities). Also reports Intel Security " +
			"Advisory IDs (e.g. INTEL-SA-00837) when applicable. In --offline " +
			"mode, shows only the raw TEE_TCB_SVN bytes.",
	},
	{
		Name:    "nvidia_payload_present",
		Tier:    2,
		Summary: "NVIDIA attestation payload present",
		Description: "Checks that the nvidia_payload field exists in the attestation " +
			"response. This payload contains GPU attestation data (either an " +
			"EAT token or JWT) that proves the inference is running on a " +
			"genuine NVIDIA GPU with confidential computing enabled.",
	},
	{
		Name:    "nvidia_signature",
		Tier:    2,
		Summary: "NVIDIA payload signature verified",
		Description: "Verifies the cryptographic signature on the NVIDIA attestation " +
			"payload. For EAT tokens, this validates SPDM ECDSA P-384 " +
			"signatures on each GPU's cert chain. For JWTs, this verifies " +
			"the token against NVIDIA's JWKS (JSON Web Key Set) endpoint.",
	},
	{
		Name:    "nvidia_claims",
		Tier:    2,
		Summary: "NVIDIA attestation claims valid",
		Description: "Validates the claims within the NVIDIA attestation payload, " +
			"including GPU architecture, driver version, and confidential " +
			"computing mode. For EAT tokens, checks per-GPU evidence " +
			"claims. For JWTs, checks the overall attestation result.",
	},
	{
		Name:    "nvidia_nonce_match",
		Tier:    2,
		Summary: "NVIDIA payload nonce matches",
		Description: "Verifies that the nonce embedded in the NVIDIA attestation " +
			"payload matches the nonce submitted by the client. This proves " +
			"the GPU attestation is fresh and was generated for this specific " +
			"verification session.",
	},
	{
		Name:    "nvidia_nras_verified",
		Tier:    2,
		Summary: "NVIDIA NRAS RIM measurement verification",
		Description: "Posts the GPU attestation evidence (EAT) to NVIDIA's Remote " +
			"Attestation Service (NRAS) for server-side measurement comparison " +
			"against NVIDIA's Reference Integrity Manifest (RIM). The RIM " +
			"contains known-good firmware hashes for each GPU model. NRAS " +
			"returns a signed JWT with the overall attestation result, which " +
			"is verified using NVIDIA's JWKS. This complements local SPDM " +
			"verification: local catches compromised evidence without trusting " +
			"NVIDIA's cloud; NRAS catches firmware measurement mismatches " +
			"that local verification cannot detect without the RIM. Skipped " +
			"in --offline mode or when the payload is JWT (already NRAS-verified).",
	},
	{
		Name:    "e2ee_capable",
		Tier:    2,
		Summary: "Signing key supports E2EE key exchange",
		Description: "Validates that the signing key is a well-formed secp256k1 " +
			"uncompressed public key suitable for ECDH key exchange. When " +
			"this passes, the proxy can establish an encrypted channel with " +
			"the enclave using ECIES (Elliptic Curve Integrated Encryption " +
			"Scheme).",
	},
	// Tier 3: Supply Chain & Channel Integrity
	{
		Name:    "tls_key_binding",
		Tier:    3,
		Summary: "No TLS key in attestation",
		Description: "No TLS certificate public key is embedded in the attestation " +
			"document. Without this, a man-in-the-middle at the vendor's load " +
			"balancer can intercept traffic even if a genuine TEE is running. " +
			"The TLS termination point is outside the attested boundary. This " +
			"is the single most critical gap for end-to-end security.",
	},
	{
		Name:    "cpu_gpu_chain",
		Tier:    3,
		Summary: "No CPU-GPU attestation binding",
		Description: "The attestation does not cryptographically bind the CPU TDX " +
			"quote to the NVIDIA GPU attestation. The two are checked in " +
			"isolation: the CPU attestation proves a trusted enclave exists, " +
			"and the GPU attestation proves a trusted GPU exists, but there " +
			"is no proof both are part of the same confidential VM. A " +
			"sophisticated attacker could mix and match attestations.",
	},
	{
		Name:    "measured_model_weights",
		Tier:    3,
		Summary: "No model weight hashes",
		Description: "The attestation does not include hashes of the model weight " +
			"files. The TDX MRTD proves the VM image is genuine (OS, " +
			"firmware, inference server), but it does not cover the model " +
			"weights loaded at runtime. Without weight measurement, a " +
			"compromised provider could load a backdoored model while " +
			"presenting valid hardware attestation. This requires runtime " +
			"measurement of weights into an RTMR register.",
	},
	{
		Name:    "build_transparency_log",
		Tier:    3,
		Summary: "No build transparency log",
		Description: "No Sigstore bundle or equivalent build transparency log entry " +
			"was found in the attestation. Venice provides a docker-compose " +
			"hash via dstack, which proves the deployment manifest hasn't " +
			"changed, but this is not an independent transparency log. " +
			"Without a reproducible build pipeline committed to an " +
			"immutable log, you cannot verify that the running code " +
			"matches a specific audited source revision.",
	},
	{
		Name:    "cpu_id_registry",
		Tier:    3,
		Summary: "CPU ID verified against Proof of Cloud",
		Description: "The CPU PPID is extracted from the PCK certificate embedded in " +
			"the TDX quote and verified against the Proof of Cloud registry " +
			"— a vendor-neutral, append-only log of hardware identities " +
			"independently verified by alliance members. When online " +
			"(default), the quote is submitted to trust-servers operated by " +
			"Secret Labs, Nillion, and iEx.ec using threshold multisig. " +
			"Use --offline to skip the registry check and show only the " +
			"extracted PPID.",
	},
}

// tierRegistry describes the three verification tiers.
var tierRegistry = [3]tierInfo{
	{
		Number: 1,
		Name:   "Core Attestation",
		Label:  "Tier 1: Core Attestation",
		Description: "Factors 1-7. Validates that a TDX quote is present, " +
			"structurally valid, properly signed by Intel hardware, and not " +
			"from a debug enclave. Also checks the nonce for replay protection " +
			"and that a signing key exists for E2EE. A Tier 1 failure means " +
			"the attestation cannot be trusted at all.",
	},
	{
		Number: 2,
		Name:   "Binding & Crypto",
		Label:  "Tier 2: Binding & Crypto",
		Description: "Factors 8-16. Validates cross-component binding: the signing " +
			"key is bound to the TDX REPORTDATA (preventing key substitution " +
			"attacks), NVIDIA GPU attestation is present and locally verified, " +
			"NVIDIA NRAS RIM measurement comparison passes, and the signing " +
			"key supports E2EE key exchange. A Tier 2 failure means the " +
			"attestation is structurally valid but may not provide the " +
			"security guarantees needed for encrypted inference.",
	},
	{
		Number: 3,
		Name:   "Supply Chain & Channel Integrity",
		Label:  "Tier 3: Supply Chain & Channel Integrity",
		Description: "Factors 17-21. The gold standard for TEE verification. " +
			"Covers TLS key binding, CPU-GPU attestation chain, measured " +
			"model weights, build transparency logs, and hardware identity " +
			"registry. No vendor passes any of these today. These represent " +
			"the future state needed for complete supply-chain verification.",
	},
}

// findFactorByName returns the factorInfo for the given name.
func findFactorByName(name string) (factorInfo, bool) {
	for _, f := range &factorRegistry {
		if f.Name == name {
			return f, true
		}
	}
	return factorInfo{}, false
}

// runHelp dispatches to the appropriate help printer.
func runHelp(args []string) {
	if len(args) == 0 {
		printOverview()
		return
	}
	switch args[0] {
	case "serve":
		printServeHelp()
	case "verify":
		printVerifyHelp()
	case "tiers":
		printTiersHelp()
	case "factors":
		printFactorsHelp()
	default:
		if f, ok := findFactorByName(args[0]); ok {
			printFactorHelp(f)
			return
		}
		fmt.Fprintf(os.Stderr, "teep help: unknown topic %q\n\n", args[0])
		printOverview()
	}
}

// printOverview prints the top-level help message.
func printOverview() {
	fmt.Print(`teep — TEE attestation verifier and E2EE proxy for AI providers

Usage:
  teep serve   [flags]                             Start the HTTP proxy server.
  teep verify  --provider NAME --model M [flags]   Fetch and print attestation report.
  teep help    [topic]                             Show detailed help for a topic.

Global flags:
  --log-level LEVEL   Set log verbosity: debug, info, warn, error (default: info).

Help topics:
  serve       Detailed documentation for the serve command.
  verify      Detailed documentation for the verify command.
  tiers       Explain the 3-tier verification scoring system.
  factors     List all 21 verification factors with full descriptions.
  <factor>    Show details for a single factor (e.g. teep help tls_key_binding).

Environment variables:
  TEEP_CONFIG        Path to TOML config file.
  TEEP_LISTEN_ADDR   Override listen address (default: 127.0.0.1:8080).
  VENICE_API_KEY     Venice AI API key.
  NEARAI_API_KEY     NEAR AI API key.
`)
}

// printServeHelp prints detailed help for the serve command.
func printServeHelp() {
	fmt.Print(`teep serve — Start the HTTP proxy server

Usage:
  teep serve [--provider NAME] [--offline] [--log-level LEVEL]

The proxy intercepts OpenAI-compatible chat completion requests, performs TEE
attestation verification against the upstream provider, and optionally enables
end-to-end encryption (E2EE) when the attestation passes.

Clients send requests to http://127.0.0.1:8080/v1/chat/completions (or the
address set by TEEP_LISTEN_ADDR) using the same format as the OpenAI API.

The proxy:
  1. Parses the model name to determine the upstream provider.
  2. Fetches and verifies TEE attestation for the provider.
  3. Caches passing attestation reports (TTL configurable).
  4. If E2EE is supported and attestation passes, encrypts the request
     body and decrypts the response using ECIES with the enclave's
     attested signing key.
  5. Forwards the request to the provider's API endpoint.

Configuration is loaded from the TOML file at $TEEP_CONFIG. Each provider
section specifies the base URL, API key, model mappings, and whether E2EE
is enabled.

Example TOML:
  [providers.venice]
  base_url = "https://api.venice.ai"
  api_key_env = "VENICE_API_KEY"
  e2ee = true

  [providers.venice.model_map]
  "gpt-4" = "e2ee-qwen3-32b"

Flags:
  --provider NAME     Run proxy with a single provider (e.g. venice, nearai).
  --offline           Skip external verification (Intel PCS, Proof of Cloud).
  --log-level LEVEL   Set log verbosity: debug, info, warn, error (default: info).
`)
}

// printVerifyHelp prints detailed help for the verify command.
func printVerifyHelp() {
	fmt.Print(`teep verify — Fetch and print a TEE attestation verification report

Usage:
  teep verify --provider NAME --model MODEL [flags]

Connects to the specified provider's attestation endpoint, fetches the TEE
attestation for the given model, and runs all 21 verification factors. The
report is printed to stdout; log messages go to stderr.

Required flags:
  --provider NAME   Provider name (e.g. venice, nearai).
  --model MODEL     Model name as known to the provider.

Optional flags:
  --save-dir DIR    Save raw attestation data to DIR (JSON, TDX quote,
                    NVIDIA payload). Useful for debugging and offline analysis.
  --offline         Skip external verification (Intel PCS collateral,
                    Proof of Cloud registry). PPID is still extracted locally.
  --log-level LEVEL Set log verbosity: debug, info, warn, error (default: info).

Exit codes:
  0   All enforced factors passed (or no factors are enforced).
  1   At least one enforced factor failed, or a fatal error occurred.

Examples:
  teep verify --provider venice --model e2ee-deepseek-r1-0528
  teep verify --provider nearai --model qwen2.5-72b-instruct --save-dir ./attestation-data
  teep verify --provider venice --model e2ee-qwen3-32b --log-level debug

See 'teep help tiers' for how factors are scored, or 'teep help factors'
for descriptions of all 21 verification factors.
`)
}

// printTiersHelp prints documentation about the 3-tier scoring system.
func printTiersHelp() {
	fmt.Print("Verification Tiers\n")
	fmt.Print(strings.Repeat("=", 19) + "\n\n")

	fmt.Print(`teep evaluates TEE attestation using 21 factors organized into 3 tiers.
Each factor produces a result: PASS, FAIL, or SKIP. Factors marked
[ENFORCED] in the report will cause the proxy to refuse requests when
they fail.

`)

	start := 0
	bounds := [3]int{7, 16, 21}
	for i, tier := range tierRegistry {
		fmt.Printf("%s\n", tier.Label)
		fmt.Print(strings.Repeat("-", len(tier.Label)) + "\n")
		fmt.Print(wrapText(tier.Description, 0, 76) + "\n\n")

		fmt.Print("  Factors:\n")
		for j := start; j < bounds[i]; j++ {
			fmt.Printf("    %2d. %-26s %s\n", j+1, factorRegistry[j].Name, factorRegistry[j].Summary)
		}
		fmt.Println()
		start = bounds[i]
	}

	fmt.Print(`Default enforced factors: nonce_match, tdx_debug_disabled,
signing_key_present, tdx_reportdata_binding. These can be overridden in
the TOML config file.

Run 'teep help factors' for full descriptions, or 'teep help <factor>'
for a single factor.
`)
}

// printFactorsHelp prints all 20 factors with full descriptions.
func printFactorsHelp() {
	fmt.Print("Verification Factors\n")
	fmt.Print(strings.Repeat("=", 20) + "\n\n")

	currentTier := 0
	for i, f := range &factorRegistry {
		if f.Tier != currentTier {
			currentTier = f.Tier
			tier := tierRegistry[currentTier-1]
			fmt.Printf("%s\n\n", tier.Label)
		}
		fmt.Printf("  %2d. %s\n", i+1, f.Name)
		fmt.Print(wrapText(f.Description, 6, 76) + "\n\n")
	}
}

// printFactorHelp prints detailed help for a single factor.
func printFactorHelp(f factorInfo) {
	tier := tierRegistry[f.Tier-1]
	fmt.Printf("%s (%s)\n", f.Name, tier.Label)
	fmt.Print(strings.Repeat("-", len(f.Name)+len(tier.Label)+3) + "\n\n")
	fmt.Print(wrapText(f.Description, 0, 76) + "\n")
}

// wrapText wraps text to the given width with the given indent. Each line
// is prefixed with indent spaces. Words are not broken.
func wrapText(text string, indent, width int) string {
	words := strings.Fields(text)
	if len(words) == 0 {
		return ""
	}

	prefix := strings.Repeat(" ", indent)
	maxLineLen := width - indent

	var b strings.Builder
	lineLen := 0

	for i, word := range words {
		wLen := len(word)
		if i == 0 {
			b.WriteString(prefix)
			b.WriteString(word)
			lineLen = wLen
			continue
		}
		if lineLen+1+wLen > maxLineLen {
			b.WriteByte('\n')
			b.WriteString(prefix)
			b.WriteString(word)
			lineLen = wLen
		} else {
			b.WriteByte(' ')
			b.WriteString(word)
			lineLen += 1 + wLen
		}
	}

	return b.String()
}
